export const abi = [
  {
    type: 'event',
    anonymous: false,
    name: 'AddAdminSuccess',
    inputs: [
      { type: 'address', name: 'account', indexed: false },
      { type: 'address', name: 'whoAdd', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'AddPKSuccess',
    inputs: [
      { type: 'address', name: 'pk', indexed: false },
      { type: 'address', name: 'whoAdd', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'ClaimSuccess',
    inputs: [
      { type: 'bytes32', name: 'id', indexed: false },
      { type: 'address', name: 'recipient', indexed: false },
      { type: 'uint256', name: 'claimed_value', indexed: false },
      { type: 'address', name: 'token_address', indexed: false },
      { type: 'address', name: 'claimer', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'CreationSuccess',
    inputs: [
      { type: 'uint256', name: 'total', indexed: false },
      { type: 'bytes32', name: 'id', indexed: false },
      { type: 'string', name: 'name', indexed: false },
      { type: 'string', name: 'message', indexed: false },
      { type: 'address', name: 'creator', indexed: false },
      { type: 'uint256', name: 'creation_time', indexed: false },
      { type: 'address', name: 'token_address', indexed: false },
      { type: 'uint256', name: 'number', indexed: false },
      { type: 'bool', name: 'ifrandom', indexed: false },
      { type: 'uint256', name: 'duration', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Initialized',
    inputs: [{ type: 'uint8', name: 'version', indexed: false }],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RefundSuccess',
    inputs: [
      { type: 'bytes32', name: 'id', indexed: false },
      { type: 'address', name: 'token_address', indexed: false },
      { type: 'uint256', name: 'remaining_balance', indexed: false },
      { type: 'address', name: 'creater', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RemoveAdminSuccess',
    inputs: [
      { type: 'address', name: 'account', indexed: false },
      { type: 'address', name: 'whoAdd', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RoleAdminChanged',
    inputs: [
      { type: 'bytes32', name: 'role', indexed: true },
      { type: 'bytes32', name: 'previousAdminRole', indexed: true },
      { type: 'bytes32', name: 'newAdminRole', indexed: true },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RoleGranted',
    inputs: [
      { type: 'bytes32', name: 'role', indexed: true },
      { type: 'address', name: 'account', indexed: true },
      { type: 'address', name: 'sender', indexed: true },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RoleRevoked',
    inputs: [
      { type: 'bytes32', name: 'role', indexed: true },
      { type: 'address', name: 'account', indexed: true },
      { type: 'address', name: 'sender', indexed: true },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'StopContractEvent',
    inputs: [{ type: 'address', name: 'whoStop', indexed: false }],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'UpdateRpRecipientsEvent',
    inputs: [
      { type: 'uint256', name: 'recipients', indexed: false },
      { type: 'address', name: 'whoStop', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'addBitverseAdmin',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'addRoot',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'check_availability',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'bytes32', name: 'id' }],
    outputs: [
      { type: 'address', name: 'token_address' },
      { type: 'uint256', name: 'balance' },
      { type: 'uint256', name: 'total' },
      { type: 'uint256', name: 'claimed' },
      { type: 'bool', name: 'expired' },
      { type: 'uint256', name: 'claimed_amount' },
    ],
  },
  {
    type: 'function',
    name: 'claim',
    constant: false,
    payable: false,
    inputs: [
      { type: 'bytes32', name: 'id' },
      { type: 'address', name: 'recipient' },
      { type: 'bytes', name: 'signedMsg' },
    ],
    outputs: [{ type: 'uint256', name: 'claimed' }],
  },
  {
    type: 'function',
    name: 'create_red_packet',
    constant: false,
    stateMutability: 'payable',
    payable: true,
    inputs: [
      { type: 'address', name: '_public_key' },
      { type: 'uint256', name: '_number' },
      { type: 'bool', name: '_ifrandom' },
      { type: 'uint256', name: '_duration' },
      { type: 'bytes32', name: '_seed' },
      { type: 'string', name: '_message' },
      { type: 'string', name: '_name' },
      { type: 'uint256', name: '_token_type' },
      { type: 'address', name: '_token_addr' },
      { type: 'uint256', name: '_total_tokens' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getRedPacketInfoById',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'bytes32', name: 'id' }],
    outputs: [
      { type: 'address', name: 'token_address' },
      { type: 'uint256', name: 'balance' },
      { type: 'uint256', name: 'total' },
      { type: 'uint256', name: 'claimed' },
      { type: 'bool', name: 'expired' },
      { type: 'uint256', name: 'claimed_amount' },
      { type: 'address', name: 'creator' },
      { type: 'bool', name: 'isRefund' },
    ],
  },
  {
    type: 'function',
    name: 'getRoleAdmin',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'bytes32', name: 'role' }],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'grantRole',
    constant: false,
    payable: false,
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'hasRole',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'initialize',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: 'root' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'isBitverseAdmin',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isBitverseRoot',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'refund',
    constant: false,
    payable: false,
    inputs: [{ type: 'bytes32', name: 'id' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'removeBitverseAdmin',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'renounceRole',
    constant: false,
    payable: false,
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'renounceRoot',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resumeContract',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokeRole',
    constant: false,
    payable: false,
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setBitversePublicKey',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: 'pk' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'stopContract',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'supportsInterface',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'bytes4', name: 'interfaceId' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'updateRpRecipients',
    constant: false,
    payable: false,
    inputs: [{ type: 'uint256', name: 'recipients' }],
    outputs: [],
  },
]
